### ISSUE TITLE
[Scrthgap] does it support  weston with GPU accelerations?

### ISSUE THREAD

**Issue by wigcheng** [renesas-rz/rz-community-bsp#5]
As title, we are evaluating RZ/V2H platform using EVK.

Official Yocto Dunfell was too old, and I saw our CPU also has Mali-G31 inside the SOC, so I would like to try this community meta layer on the EVK.

After tweak using RZ/V2L machine conf, the meta-layer, renesas-image-minimal image works fine.
But renesas-image-demo cannot boot into login promt as follows error messages:

[  OK  ] Reached target Login Prompts.
         Starting Weston, a Wayland compositor, as a system service...
[  OK  ] Started User Login Management.
[  OK  ] Started D-Bus System Message Bus.
[  OK  ] Started Telephony service.
[  OK  ] Started Avahi mDNS/DNS-SD Stack.
[  OK  ] Reached target Multi-User System.
[  OK  ] Created slice User Slice of UID 1000.
         Starting User Runtime Directory /run/user/1000...
[  OK  ] Finished User Runtime Directory /run/user/1000.
         Starting User Manager for UID 1000...
[   15.590451] audit: type=1006 audit(1709054774.584:13): pid=349 uid=0 subj=kernel old-auid=4294967295 auid=1000 tty=(none) old-ses=4294967295 ses=1 res=1
[   15.847315] audit: type=1334 audit(1709054774.840:14): prog-id=17 op=LOAD
[   15.854669] audit: type=1334 audit(1709054774.840:15): prog-id=17 op=UNLOAD
[  OK  ] Started User Manager for UID 1000.
**[  OK  ] Started Session c1 of User weston.**

Yes, it hangs.... I think it's due to weston trying to link HW accelerations.
and I'm pretty sure Panfrost driver already be enabled in kernel config, BTW, my kernel is adapts renesas official kernel 5.10.145-cip17.

My question is that weston version too new, cause incompatible with kernel 5.10? Do you have any directions?
In addition, I plan downgrade to Kirkstone and try again, is it possible works?

Thanks a lot

**Comment by seebe** [comment]
Hello.

I don't think anyone has tried the community BSP with RZ/V2H yet.

But, we have seen issues with Panfrost with the 5.10 kernel when testing with RZ/G2L and RZ/V2L. There are mainline kernel patches that would haver to be backported to 5.10 to get full Panfrost support. Therefore, we only use kernel version 6.1 or 6.12 if we want GPU/Panfrost support in the Community BSP.

**Comment by wigcheng** [comment]
Got it, I appreciate for your comments, so there's some ways can try as following:
1.  Backport mainline kernel patches of Panfrost to Renases kernel 5.10, it is possible works, at least you tested before!
But do you have a specfic mainline kernel version to me? I think it worth to try!!
2. Adapts mainline kernel 6.1 or 6.12, but it seems does not support RZ/V2H yet, right?

I know no one tried community meta-layer with RZ/V2H yet, but precisely because of this, my experiment holds value, and I also hope it can contribute to the community, thanks!

**Comment by seebe** [comment]
1, Sorry, we never tried it. We figured it was too much work, and Renesas is moving away from the 5.10 kernel anyway.

2, Correct. RZ/V2H is brand new so mainlining has just started. But in 2025, Renesas will be putting together a 6.1 and 6.12 kernel for the RZ/V2H.

**Comment by wigcheng** [comment]
Understood! I have to replan the software roadmap for our RZ/V2H product, thanks for your information, very useful.
I will close this issue, thanks!
